//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelterApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adoption
    {
        public int AdoptionID { get; set; }
        public int PetID { get; set; }
        public int FamilyID { get; set; }
        public System.DateTime DateAdopted { get; set; }
        public string EmployeeName { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual Pet4 Pet4 { get; set; }
    }
}
